/**
 * Bakes Natural Earth land data into `public/globe.json`.
 *
 * Run only when the source data changes:
 *   bun tools/build-globe.ts path/to/ne_110m_land.json
 *
 * Why bake instead of fetching at runtime: WebEye is self-hosted, and a landing
 * page that calls out to raw.githubusercontent.com on every visit would break on
 * air-gapped installs, leak visitors to a third party, and add a failure mode to
 * a page whose whole job is to look reliable. The halftone dot grid is also
 * precomputed here — point-in-polygon over ~29k grid cells is fine once in a
 * build script and wasteful on every page load.
 *
 * Output is Int16 (degrees × 100) packed as base64, which the browser decodes in
 * one pass with no parsing cost.
 */

const src = process.argv[2];
if (!src) {
  console.error("usage: bun tools/build-globe.ts <ne_110m_land.json>");
  process.exit(1);
}

type Ring = number[][];
const geo = JSON.parse(await Bun.file(src).text());

// --- collect rings --------------------------------------------------------

const polygons: Ring[][] = [];
for (const f of geo.features) {
  const g = f.geometry;
  if (g.type === "Polygon") polygons.push(g.coordinates);
  else if (g.type === "MultiPolygon") polygons.push(...g.coordinates);
}

/** Drop rings too small to read at landing-page size (tiny islets). */
function ringArea(ring: Ring) {
  let a = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    a += (ring[j][0] - ring[i][0]) * (ring[j][1] + ring[i][1]);
  }
  return Math.abs(a / 2);
}

const kept = polygons.filter((p) => ringArea(p[0]) > 1.2);

// --- point in polygon -----------------------------------------------------

function inRing(x: number, y: number, ring: Ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

/** Outer ring contains the point and no hole excludes it. */
function onLand(x: number, y: number) {
  for (const poly of kept) {
    if (!inRing(x, y, poly[0])) continue;
    let hole = false;
    for (let i = 1; i < poly.length; i++) {
      if (inRing(x, y, poly[i])) {
        hole = true;
        break;
      }
    }
    if (!hole) return true;
  }
  return false;
}

// --- halftone grid --------------------------------------------------------
// Longitude spacing widens by 1/cos(lat) so dots stay evenly spaced on the
// sphere. A plain lat/lng grid bunches them into a dense smear at the poles.

const STEP = 1.6;
const dots: number[] = [];

for (let lat = -84; lat <= 84; lat += STEP) {
  const lngStep = STEP / Math.max(0.15, Math.cos((lat * Math.PI) / 180));
  for (let lng = -180; lng < 180; lng += lngStep) {
    if (onLand(lng, lat)) {
      dots.push(Math.round(lng * 100), Math.round(lat * 100));
    }
  }
}

// --- outlines -------------------------------------------------------------
// Keep every Nth vertex; at this radius the dropped detail is sub-pixel.

const outlines: number[][] = [];
for (const poly of kept) {
  for (const ring of poly) {
    const flat: number[] = [];
    const stride = ring.length > 400 ? 3 : ring.length > 150 ? 2 : 1;
    for (let i = 0; i < ring.length; i += stride) {
      flat.push(Math.round(ring[i][0] * 100), Math.round(ring[i][1] * 100));
    }
    // close the ring
    flat.push(Math.round(ring[0][0] * 100), Math.round(ring[0][1] * 100));
    if (flat.length >= 6) outlines.push(flat);
  }
}

const b64 = (nums: number[]) =>
  Buffer.from(new Int16Array(nums).buffer).toString("base64");

const out = {
  note: "Generated by tools/build-globe.ts from Natural Earth 110m land (public domain). Int16 degrees x100, base64.",
  dots: b64(dots),
  outlines: outlines.map(b64),
};

await Bun.write("public/globe.json", JSON.stringify(out));

const bytes = (await Bun.file("public/globe.json").text()).length;
console.log(
  `polygons kept: ${kept.length}\n` +
    `dots:          ${dots.length / 2}\n` +
    `outline rings: ${outlines.length}\n` +
    `globe.json:    ${(bytes / 1024).toFixed(1)} KB`,
);
